### ISSUE TITLE
Unable to pack the package

### ISSUE THREAD

**Issue by proll** [okviz/BulletChart#1]
```
[~/proj/BulletChart]$ pbiviz package
 info   Building visual...
 error  UNKNOWN { [Error: ENOENT: no such file or directory, stat '/Users/proll/proj/libraries/jquery-3.1.1.min.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/proll/proj/libraries/jquery-3.1.1.min.js' }
```

Seems to be you have ../libraries/jquery-3.1.1.min.js link to the jquery lib, use npm for example as external library manager

**Comment by danieleperilli** [comment]
Why? We several visuals that share the same modules. If we use the nude_modules folder, then we have to maintain it for every visual. Our libraries are accessible here: https://github.com/okviz/Libraries

**Comment by proll** [comment]
oh ok,
It's not critical. But at least description of dependencies and installation guide would be awesome to have in README.md.
