### ISSUE TITLE
Cannot see comparison value field in Power BI desktop

### ISSUE THREAD

**Issue by namratalamba92** [okviz/BulletChart#12]
I'm trying to create something like the attached, however, I'm not able to insert the comparison value to do the same.
[Phase II mocks_git.pptx](https://github.com/okviz/BulletChart/files/1990177/Phase.II.mocks_git.pptx)

**Comment by danieleperilli** [comment]
You can see multiple bars only within same category - to do that, you have to bind the category field to a column.
