### ISSUE TITLE
Multiple target comparison

### ISSUE THREAD

**Issue by Romek7691** [okviz/BulletChart#13]
Hi,
Your Bullet Chart visual is great, especially the possibility of using more than one target. But - do you plan to allow more than one comparison direction? Different comparison for each target? Now there is only one that works for all targets - and there is no way to change bar colors for situation where value is greater than one target and less than the other one and keep standard bar color when value is between targets.

**Comment by danieleperilli** [comment]
At the moment we don't any plan to add this feature, but we could add it in the future. It depends on user requests.
