### ISSUE TITLE
legend doesn't always reflect correct colors

### ISSUE THREAD

**Issue by smatson18** [okviz/BulletChart#14]
It appears that if I choose a target value and have the indicator as the square of the circle, the Marker Color doesn't change the color of the legend.  The color is correct in the visual itself, but the legend color doesn't reflect the color.
![untitled](https://user-images.githubusercontent.com/38441109/40549737-d8aa5120-5ffd-11e8-8d6d-92489430357f.png)

**Comment by danieleperilli** [comment]
Please provide a repro and re-open the issue.
