### ISSUE TITLE
Target color option disappears when using catagory from joined table

### ISSUE THREAD

**Issue by listay** [okviz/BulletChart#16]
Using Direct Query mode to SQL database server. May 2018 PBI version. Current version of bullet chart from marketplace. Have Fact table that contains Rate (Value) and Target (Avg of Column Value). Fact table joined to Department dimension table. When no category is selected, the target color is visible. When I use department name field from the department table in the Category selection, the target color disappears. Since using direct query, can't really send the pbix file. Attaching screenshots.

BTW - If I change the color to red for example with no category selected first, then add the category field, the functionality works (bar turns red if not meeting target), but color option still disappears after category added.
[Screenshots.docx](https://github.com/okviz/BulletChart/files/2099353/Screenshots.docx)

**Comment by danieleperilli** [comment]
Please provide a repro and re-open the issue.
