### ISSUE TITLE
Duplicating values on axis

### ISSUE THREAD

**Issue by bjnodello** [okviz/BulletChart#17]
There are duplicate values showing up on the axis.  Doesn't happen all the time, may just be with small values?  The values are whole numbers.

![bullet chart issue](https://user-images.githubusercontent.com/36570941/41671149-1bbd4734-746b-11e8-982b-d5364a9b32ec.PNG)

![bullet chart issue 2](https://user-images.githubusercontent.com/36570941/41671290-8708d74c-746b-11e8-8c44-38dce51078d1.PNG)

Thanks,

Brett

**Comment by danieleperilli** [comment]
Please provide a repro and re-open the issue.
