### ISSUE TITLE
Locale support

### ISSUE THREAD

**Issue by danchristo** [okviz/BulletChart#19]
The custom visual does not reflect the current locale (i.e. for the Display Units).
This is true for PBI Desktop & Service.

![grafik](https://user-images.githubusercontent.com/40884659/42367726-6a72eaae-8105-11e8-959c-91a9ab0dd216.png)

**Comment by danieleperilli** [comment]
Unfortunately, this is an issue in the formatting library. We will improve this in a future update. Thanks for reporting.
