### ISSUE TITLE
Bar Does not Change Colour if Target is Blank

### ISSUE THREAD

**Issue by kcinmelbourne** [okviz/BulletChart#33]
Hi guys,

I have a situation where I am looking to have the bar turn red if it exceeds the target. It works fine unless there isn't a target (target = BLANK()).  I'd expect this would be treat as zero but it isn't and the bar remains black.  Hoping I'm just using this incorrectly as I've just built a suite of dashboards using this.

I tried to upload a sample file but it doesn't accept pbix. Screenshot below instead where A turns red for exceeding target and B remains black as there isn't a target.

![image](https://user-images.githubusercontent.com/41977482/53731183-4e01e980-3ebd-11e9-9ee1-dd60f89c4cbd.png)

Thanks in advance for your assistance.
KC

**Comment by danieleperilli** [comment]
We can't assume Target is 0 if it is BLANK, sorry. But you can do it by creating a calculated measure in DAX.

**Comment by kcinmelbourne** [comment]
Thanks Daniele for your quick response. If there is any chance of this being considered for future releases, that would be amazing (unless it is a technical limitation).  As I'm sure you can appreciate, having to adjust our measures for this isn't ideal but the visual is otherwise fantastic.
