### ISSUE TITLE
visual error when targets field measure encounter a BLANK value

### ISSUE THREAD

**Issue by thej4ck** [okviz/BulletChart#6]
Hi.
I found this visual bug that i actually worked around. I'll share my experience just to let it know.
Let's say i have this simple data:
apple, 10, 20
pear, 10, BLANK
donuts, 30, 40

if i put first column in CATEGORY,second column in Value, and third in Targets, the visuals shows only 1 BAR.
It seems that a BLANK value in targets blocks the visual elaboration.
I worked araound it trasforming BLANK to zeroes...

**Comment by danieleperilli** [comment]
Thanks for reporting. It is already solved in the v2.1

**Comment by thej4ck** [comment]
Grandeeee
