### ISSUE TITLE
This visual inside PowerBi mobile app is growing insane

### ISSUE THREAD

**Issue by thej4ck** [okviz/BulletChart#7]
Some screenshots taken in sequence on my mobile app.
I think it's not a feature :-)

![img_6087](https://cloud.githubusercontent.com/assets/5577620/22875975/ae4765b0-f1ce-11e6-8aca-80a2642032aa.png)
![img_6088](https://cloud.githubusercontent.com/assets/5577620/22875974/ae418046-f1ce-11e6-9a35-14d1fc8eecfe.png)
![img_6089](https://cloud.githubusercontent.com/assets/5577620/22875973/ae2bb34c-f1ce-11e6-9534-3b783d3fb317.png)
![img_6090](https://cloud.githubusercontent.com/assets/5577620/22875972/ae230116-f1ce-11e6-9916-6964bfbaa954.png)
![img_6091](https://cloud.githubusercontent.com/assets/5577620/22875971/ae06e60c-f1ce-11e6-8247-59a68d7c233a.png)

**Comment by okviz** [comment]
Unfortunately, the bug affect several custom visuals and we have no way to debug issues on iOS platform. We are investigating with Power BI support team.

**Comment by okviz** [comment]
Just fixed.

**Comment by thej4ck** [comment]
Thank you.
